### ISSUE TITLE
using angular-selectbox in angular.modal not working

### ISSUE THREAD

**Issue by hrofe** [milica/angular-selectbox#4] opened 2015-11-09 08:42 UTC
Dear milica,
The plug-in that you have created is awesome, but I encounter with problem using it in angular. Modal.
When I want to use it in modal and use it as multi-select I have an error:
TypeError: Cannot read property 'indexOf' of undefined
    at selectbox.js?01:12

**Comment by milica** [comment] 2015-11-09 20:23
Hello there :)

Can you show me the code? I mean, how are you trying to initiate it?

**Comment by hrofe** [comment] 2015-11-10 07:11
hey, i'm attaching 2 examples that i'm using:
1. using selectbox without angular.modal - this works perfect
2. using selectbox inside angular.modal - not working
   
   **first example ( selectbox  not in angular.modal):**

html:

``` html
<div class="divFloatRight">
    <selectbox list="sbAreas"
               ng-model="organization.SelectedOrganizationAreas"
               title='TITLE' // this is an attribute that i added when i want to show other title in multi select
               multi="true"
               scalss="projectInfo-selectbox-toggle" />
</div>
```

javascript:

``` javascript

//i map my array (areas) to new array

    $scope.sbAreas = $scope.areas.map(function (obj) {
    var rObj = {};
    rObj.id = obj.OrganizationAreaId;
    rObj.name = obj.Area;
    return rObj;
    });

```
- this example works perfectly!!!!!!

**second example (selectbox in angular.modal):**

html:

``` html
<script type="text/ng-template" id="EditPermissionModal.html">
        <div class="organization-modal-header">
            <div class="pull-left" ng-click="cancel()">
                <img src="/Images/projects/cross.png" class="img-responsive" alt="" />
            </div>
            <h1 class="modal-title">permissions</h1>
        </div>
        <div class="modal-body">
            <div class="row divBottomPadding" style="text-align:center;">
                <div class=""></div>
                <div class="">
                    <selectbox list="sbProfs"
                               ng-model="editedUser.Details.SelectedOrganizationPermissions"
                               title='permissions'
                               multi="true"
                               scalss="projectInfo-selectbox-toggle"
                                />
                </div>
            </div>
        </div>
        <div class="organization-modal-footer">
            <div class="icons text-center">
                <button class="btn btn-primary addResponsibility" ng-click="saveEmployee()">
                    <h3 class="modal-title">save changes </h3>
                </button>
            </div>
        </div>
</script>
```

javascript:

``` javascript

    $scope.sbPermmisions = $scope.orgPermissions.map(function (obj) {
                    var rObj = {};
                    rObj.id = obj.OrganizationPermissionId;
                    rObj.name = obj.Title;
                    return rObj;
                });

// init modal 
    $scope.editUserPermissions = function (employee) {
                var modalInstance = $modal.open({
                    //windowClass: "modal flip",
                    templateUrl: 'EditPermissionModal.html',
                    controller: EditUserPermissionsModalInstanceCtrl,
                    scope: $scope,
                    resolve: {
                        modalEmployee: function () {
                            return employee;
                        },
                        modalPermissions: function () { return $scope.orgPermissions; },
                        modalsbPermissions: function () { return $scope.sbPermmisions; }
                    }
                });

                modalInstance.result.then(function (user) {
                    //console.log(user);
                    $scope.updateEmployeePermissions(user);
                    // $scope.editEmployee(user);
                });
    };

//modal function
    var EditUserPermissionsModalInstanceCtrl = function ($scope, $modalInstance, modalEmployee,   modalPermissions, modalsbPermissions) {

    $scope.editedUser = modalEmployee;
    $scope.permissions = modalPermissions;
    $scope.sbProfs = modalsbPermissions;

    /* Modal Functions*/

    $scope.saveEmployee = function () {
        console.log($scope.editedUser);
        $modalInstance.close($scope.editedUser);
    };

    $scope.cancel = function () {
        $modalInstance.dismiss('cancel');
    };
    };

```

**when i open the modal and click on the selectbox i get the error:**
**TypeError: Cannot read property 'indexOf' of undefined
    at selectbox.js?01:12
    at angular.js:12214
    at Array.w.constant (angular.js:12257)
    at Object.<anonymous> (angular.js:12831)
    at n.$digest (angular.js:14300)
    at n.$apply (angular.js:14571)
    at angular.js:16308
    at e (angular.js:4924)
    at angular.js:5312**

**Comment by milica** [comment] 2015-11-10 12:02
It looks like array is not passed properly to the modal, I'll take a closer look a bit later and let you know! Just a heads up, soon I'll release new version (which supposed to be long time ago), and I'll publish it to bower. It's work in progress and I hope I'll release it soon. 
But in the meantime I'll try to reproduce this case and fix the bug... Stay tuned!

**Comment by milica** [comment] 2015-11-10 20:47
hey @hrofe I just pushed some changes. There was a pull request which I merged without taking deeper look into it which also broke stuff. Can you pull newest version and see if you still have the issue? 
I just tried with bootstrap's modal and it works fine.

**Comment by hrofe** [comment] 2015-11-11 09:28
hey @milica i just pull the newest virson and it works perfectly. thanx :+1: 
i also commit change  that user can change the css Class to different selectbox.

**Closed as completed** 2015-11-15 18:43 UTC
